In [9]:
import pandas as pd

data = pd.read_excel("sample_50x10_data.xlsx")

#print(data)
# print(data.head(10))        # to print top 10 data from the file (used in files with large number of data)
# print(data.tail(10))
display(data.head())
display(data.tail())

,ID,Name,Age,Course,Marks,City,Attendance,Projects,Internship,Placement
0,1,Simran,18,Python,85,Kolkata,100,1,No,Not Placed
1,2,Rohan,24,Statistics,85,Jaipur,83,10,Yes,Placed
2,3,Ananya,23,Machine Learning,98,Delhi,79,8,Yes,Not Placed
3,4,Priya,18,Data Science,89,Kolkata,88,2,No,Placed
4,5,Karan,25,Data Analytics,62,Pune,75,3,No,Placed

,ID,Name,Age,Course,Marks,City,Attendance,Projects,Internship,Placement
45,46,Rahul,21,Machine Learning,93,Hyderabad,78,8,No,Placed
46,47,Rohan,24,Deep Learning,91,Kolkata,77,10,Yes,Not Placed
47,48,Arjun,18,Data Science,62,Bangalore,82,3,No,Not Placed
48,49,Rohan,25,Power BI,98,Jaipur,74,4,Yes,Placed
49,50,Alex,23,Deep Learning,90,Mumbai,99,5,No,Not Placed

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          50 non-null     int64
 1   Name        50 non-null     object
 2   Age         50 non-null     int64
 3   Course      50 non-null     object
 4   Marks       50 non-null     int64
 5   City        50 non-null     object
 6   Attendance  50 non-null     int64
 7   Projects    50 non-null     int64
 8   Internship  50 non-null     object
 9   Placement   50 non-null     object
dtypes: int64(5), object(5)
memory usage: 4.0+ KB

In [15]:
data.describe()

             ID        Age      Marks  Attendance  Projects
count  50.00000  50.000000   50.00000   50.000000  50.00000
mean   25.50000  22.040000   80.68000   84.020000   5.56000
std    14.57738   2.203522   12.53638    9.579932   2.99087
min     1.00000  18.000000   60.00000   70.000000   1.00000
25%    13.25000  21.000000   66.25000   77.000000   3.25000
50%    25.50000  22.500000   85.00000   81.500000   5.00000
75%    37.75000  24.000000   90.00000   92.000000   8.00000
max    50.00000  25.000000  100.00000  100.000000  10.00000

In [ ]:
data.isnull().sum()     # tells how many null values we have

ID            0
Name          0
Age           0
Course        0
Marks         0
City          0
Attendance    0
Projects      0
Internship    0
Placement     0
dtype: int64